### ISSUE TITLE
Create the ability to unpause a given region 

### ISSUE THREAD

**Issue by mischat** [bosonprotocol/boson-protocol-contracts#672] opened 2023-06-07 23:46 UTC
We only, currently, have an unpause all method ... whilst doing surgery might be good to have more fine grained controls

**Comment by anajuliabit** [comment] 2023-06-08 02:00
@mischat we already have a PR open implementing this 

https://github.com/bosonprotocol/boson-protocol-contracts/pull/644

**Comment by zajck** [comment] 2023-06-08 05:40
Duplicate of #631

**Closed by zajck** 2023-06-08 05:40 UTC
Labels: enhancement
